// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/admin/[...catchall].tsx";
import * as $3 from "./routes/api/calc.tsx";
import * as $4 from "./routes/api/case.tsx";
import * as $5 from "./routes/api/leads.tsx";
import * as $6 from "./routes/api/ranking.ts";
import * as $7 from "./routes/api/webinar.tsx";
import * as $8 from "./routes/docs/[...slug].tsx";
import * as $9 from "./routes/gfm.css.ts";
import * as $10 from "./routes/hackathon4.ts";
import * as $11 from "./routes/index.tsx";
import * as $12 from "./routes/proxy/image/index.tsx";
import * as $$0 from "./islands/CampHeader.tsx";
import * as $$1 from "./islands/CampMentor.tsx";
import * as $$2 from "./islands/Case.tsx";
import * as $$3 from "./islands/ChangeDevice.tsx";
import * as $$4 from "./islands/ChangeTheme.tsx";
import * as $$5 from "./islands/Cms.tsx";
import * as $$6 from "./islands/ContactUs.tsx";
import * as $$7 from "./islands/Content.tsx";
import * as $$8 from "./islands/FaviconImage.tsx";
import * as $$9 from "./islands/Header.tsx";
import * as $$10 from "./islands/HelpFaq.tsx";
import * as $$11 from "./islands/ImpactCalculator.tsx";
import * as $$12 from "./islands/LiveProjects.tsx";
import * as $$13 from "./islands/OnThisPage.tsx";
import * as $$14 from "./islands/PopularDocuments.tsx";
import * as $$15 from "./islands/RankingAnalyze.tsx";
import * as $$16 from "./islands/RankingHeader.tsx";
import * as $$17 from "./islands/Sidebar.tsx";
import * as $$18 from "./islands/SliderJS.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/admin/[...catchall].tsx": $2,
    "./routes/api/calc.tsx": $3,
    "./routes/api/case.tsx": $4,
    "./routes/api/leads.tsx": $5,
    "./routes/api/ranking.ts": $6,
    "./routes/api/webinar.tsx": $7,
    "./routes/docs/[...slug].tsx": $8,
    "./routes/gfm.css.ts": $9,
    "./routes/hackathon4.ts": $10,
    "./routes/index.tsx": $11,
    "./routes/proxy/image/index.tsx": $12,
  },
  islands: {
    "./islands/CampHeader.tsx": $$0,
    "./islands/CampMentor.tsx": $$1,
    "./islands/Case.tsx": $$2,
    "./islands/ChangeDevice.tsx": $$3,
    "./islands/ChangeTheme.tsx": $$4,
    "./islands/Cms.tsx": $$5,
    "./islands/ContactUs.tsx": $$6,
    "./islands/Content.tsx": $$7,
    "./islands/FaviconImage.tsx": $$8,
    "./islands/Header.tsx": $$9,
    "./islands/HelpFaq.tsx": $$10,
    "./islands/ImpactCalculator.tsx": $$11,
    "./islands/LiveProjects.tsx": $$12,
    "./islands/OnThisPage.tsx": $$13,
    "./islands/PopularDocuments.tsx": $$14,
    "./islands/RankingAnalyze.tsx": $$15,
    "./islands/RankingHeader.tsx": $$16,
    "./islands/Sidebar.tsx": $$17,
    "./islands/SliderJS.tsx": $$18,
  },
  baseUrl: import.meta.url,
};

export default manifest;
