// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { DecoManifest } from "$live/types.ts";

import * as $0 from "./functions/LoadGitHubRaw.ts";
import * as $$$$0 from "./routes/index.tsx";
import * as $$$$1 from "./routes/[...catchall].tsx";
import * as $$$$2 from "./routes/_app.tsx";
import * as $$$$3 from "./routes/_middleware.ts";
import * as $$$$$0 from "./islands/Cms.tsx";
import * as $$$$$1 from "./islands/Header.tsx";
import * as $$$$$2 from "./islands/LiveControls.tsx";
import * as $$$$$3 from "./islands/SliderJS.tsx";
import * as $$$$$$$$0 from "./sections/About.tsx";
import * as $$$$$$$$1 from "./sections/Carousel.tsx";
import * as $$$$$$$$2 from "./sections/Cms.tsx";
import * as $$$$$$$$3 from "./sections/Community.tsx";
import * as $$$$$$$$4 from "./sections/Delight.tsx";
import * as $$$$$$$$5 from "./sections/Divider.tsx";
import * as $$$$$$$$6 from "./sections/Faq.tsx";
import * as $$$$$$$$7 from "./sections/Features.tsx";
import * as $$$$$$$$8 from "./sections/Footer.tsx";
import * as $$$$$$$$9 from "./sections/Head.tsx";
import * as $$$$$$$$10 from "./sections/Header.tsx";
import * as $$$$$$$$11 from "./sections/Integration.tsx";
import * as $$$$$$$$12 from "./sections/Markdown.tsx";
import * as $$$$$$$$13 from "./sections/Partner.tsx";
import * as $$$$$$$$14 from "./sections/QuillText.tsx";
import * as $live_workbench from "$live/routes/live/workbench.ts";
import * as $live_editorData from "$live/routes/live/editorData.ts";
import * as $live_inspect from "$live/routes/live/inspect.ts";
import * as $live_meta from "$live/routes/live/_meta.ts";
import * as $live_previews from "$live/routes/live/previews/[...block].tsx";

const manifest: DecoManifest = {
  "functions": {
    "deco-sites/starting/functions/LoadGitHubRaw.ts": $0,
  },
  "routes": {
    "./routes/index.tsx": $$$$0,
    "./routes/[...catchall].tsx": $$$$1,
    "./routes/_app.tsx": $$$$2,
    "./routes/_middleware.ts": $$$$3,
    "./routes/live/workbench.ts": $live_workbench,
    "./routes/live/editorData.ts": $live_editorData,
    "./routes/live/inspect.ts": $live_inspect,
    "./routes/live/_meta.ts": $live_meta,
    "./routes/live/previews/[...block].tsx": $live_previews,
  },
  "islands": {
    "./islands/Cms.tsx": $$$$$0,
    "./islands/Header.tsx": $$$$$1,
    "./islands/LiveControls.tsx": $$$$$2,
    "./islands/SliderJS.tsx": $$$$$3,
  },
  "sections": {
    "deco-sites/starting/sections/About.tsx": $$$$$$$$0,
    "deco-sites/starting/sections/Carousel.tsx": $$$$$$$$1,
    "deco-sites/starting/sections/Cms.tsx": $$$$$$$$2,
    "deco-sites/starting/sections/Community.tsx": $$$$$$$$3,
    "deco-sites/starting/sections/Delight.tsx": $$$$$$$$4,
    "deco-sites/starting/sections/Divider.tsx": $$$$$$$$5,
    "deco-sites/starting/sections/Faq.tsx": $$$$$$$$6,
    "deco-sites/starting/sections/Features.tsx": $$$$$$$$7,
    "deco-sites/starting/sections/Footer.tsx": $$$$$$$$8,
    "deco-sites/starting/sections/Head.tsx": $$$$$$$$9,
    "deco-sites/starting/sections/Header.tsx": $$$$$$$$10,
    "deco-sites/starting/sections/Integration.tsx": $$$$$$$$11,
    "deco-sites/starting/sections/Markdown.tsx": $$$$$$$$12,
    "deco-sites/starting/sections/Partner.tsx": $$$$$$$$13,
    "deco-sites/starting/sections/QuillText.tsx": $$$$$$$$14,
  },
  "config": config,
  "baseUrl": import.meta.url,
};

export default manifest;
