// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./functions/LoadGitHubRawPost.ts";
import * as $1 from "./functions/LoadGitHubRaw.ts";
import * as $2 from "./functions/psiRankingList.ts";
import * as $3 from "./functions/LoadPageProps.ts";
import * as $4 from "./functions/LoadGitHubRawPostList.ts";
import * as $$$0 from "./loaders/denoTopicsLoader.ts";
import * as $$$1 from "./loaders/blogPostLoader.ts";
import * as $$$2 from "./loaders/blogPostDetailsLoader.ts";
import * as $$$3 from "./loaders/featuredPosts.ts";
import * as $$$4 from "./loaders/blogPostMarkdownLoader.ts";
import * as $$$5 from "./loaders/denoLoader.ts";
import * as $$$$0 from "./routes/index.tsx";
import * as $$$$1 from "./routes/gfm.css.ts";
import * as $$$$2 from "./routes/proxy/image/index.tsx";
import * as $$$$3 from "./routes/admin/[...catchall].tsx";
import * as $$$$4 from "./routes/hackathon4.ts";
import * as $$$$5 from "./routes/_middleware.ts";
import * as $$$$6 from "./routes/docs/[...slug].tsx";
import * as $$$$7 from "./routes/api/case.tsx";
import * as $$$$8 from "./routes/api/webinar.tsx";
import * as $$$$9 from "./routes/api/ranking.ts";
import * as $$$$10 from "./routes/api/calc.tsx";
import * as $$$$11 from "./routes/api/leads.tsx";
import * as $$$$12 from "./routes/_app.tsx";
import * as $$$$$0 from "./islands/OnThisPage.tsx";
import * as $$$$$1 from "./islands/Case.tsx";
import * as $$$$$2 from "./islands/FaviconImage.tsx";
import * as $$$$$3 from "./islands/ImpactCalculator.tsx";
import * as $$$$$4 from "./islands/Content.tsx";
import * as $$$$$5 from "./islands/CampHeader.tsx";
import * as $$$$$6 from "./islands/LiveProjects.tsx";
import * as $$$$$7 from "./islands/ChangeTheme.tsx";
import * as $$$$$8 from "./islands/Cms.tsx";
import * as $$$$$9 from "./islands/PopularDocuments.tsx";
import * as $$$$$10 from "./islands/ContactUs.tsx";
import * as $$$$$11 from "./islands/SliderJS.tsx";
import * as $$$$$12 from "./islands/ChangeDevice.tsx";
import * as $$$$$13 from "./islands/Header.tsx";
import * as $$$$$14 from "./islands/Sidebar.tsx";
import * as $$$$$15 from "./islands/CampMentor.tsx";
import * as $$$$$16 from "./islands/HelpFaq.tsx";
import * as $$$$$17 from "./islands/RankingAnalyze.tsx";
import * as $$$$$18 from "./islands/RankingHeader.tsx";
import * as $$$$$$$$0 from "./sections/PopularTopics.tsx";
import * as $$$$$$$$1 from "./sections/CampHero.tsx";
import * as $$$$$$$$2 from "./sections/MarkdownContent.tsx";
import * as $$$$$$$$3 from "./sections/OnThisPage.tsx";
import * as $$$$$$$$4 from "./sections/QuillText.tsx";
import * as $$$$$$$$5 from "./sections/HeroPost.tsx";
import * as $$$$$$$$6 from "./sections/Home/Brands.tsx";
import * as $$$$$$$$7 from "./sections/StripePricing.tsx";
import * as $$$$$$$$8 from "./sections/CampComments.tsx";
import * as $$$$$$$$9 from "./sections/BlogHeader.tsx";
import * as $$$$$$$$10 from "./sections/RankingList.tsx";
import * as $$$$$$$$11 from "./sections/Pricing.tsx";
import * as $$$$$$$$12 from "./sections/SectionList.tsx";
import * as $$$$$$$$13 from "./sections/HowCanWeHelp.tsx";
import * as $$$$$$$$14 from "./sections/Webinar/Hero.tsx";
import * as $$$$$$$$15 from "./sections/Webinar/Content.tsx";
import * as $$$$$$$$16 from "./sections/BlogPostList.tsx";
import * as $$$$$$$$17 from "./sections/JoinOurCommunity.tsx";
import * as $$$$$$$$18 from "./sections/PricingValue.tsx";
import * as $$$$$$$$19 from "./sections/ImpactCalculator.tsx";
import * as $$$$$$$$20 from "./sections/BlogPostHeader.tsx";
import * as $$$$$$$$21 from "./sections/Features.tsx";
import * as $$$$$$$$22 from "./sections/CampSteps.tsx";
import * as $$$$$$$$23 from "./sections/Markdown.tsx";
import * as $$$$$$$$24 from "./sections/General/Spacer.tsx";
import * as $$$$$$$$25 from "./sections/Content.tsx";
import * as $$$$$$$$26 from "./sections/HelpBlogPosts.tsx";
import * as $$$$$$$$27 from "./sections/CampRegistration.tsx";
import * as $$$$$$$$28 from "./sections/Community.tsx";
import * as $$$$$$$$29 from "./sections/Divider.tsx";
import * as $$$$$$$$30 from "./sections/Partner.tsx";
import * as $$$$$$$$31 from "./sections/Differentials.tsx";
import * as $$$$$$$$32 from "./sections/Cms.tsx";
import * as $$$$$$$$33 from "./sections/Footer.tsx";
import * as $$$$$$$$34 from "./sections/Head.tsx";
import * as $$$$$$$$35 from "./sections/PopularDocuments.tsx";
import * as $$$$$$$$36 from "./sections/Integration.tsx";
import * as $$$$$$$$37 from "./sections/ContactUs.tsx";
import * as $$$$$$$$38 from "./sections/BlogPostSEO.tsx";
import * as $$$$$$$$39 from "./sections/FooterBigLogo.tsx";
import * as $$$$$$$$40 from "./sections/Header.tsx";
import * as $$$$$$$$41 from "./sections/Case/ArticleYoutubeVideo.tsx";
import * as $$$$$$$$42 from "./sections/Case/Case.tsx";
import * as $$$$$$$$43 from "./sections/Case/ArticleBannerCTA.tsx";
import * as $$$$$$$$44 from "./sections/Case/ArticleHeader.tsx";
import * as $$$$$$$$45 from "./sections/Case/ArticleQuote.tsx";
import * as $$$$$$$$46 from "./sections/Case/ArticleVideo.tsx";
import * as $$$$$$$$47 from "./sections/Case/ArticleParagraph.tsx";
import * as $$$$$$$$48 from "./sections/Case/ArticleDivider.tsx";
import * as $$$$$$$$49 from "./sections/Case/ArticleNumbers.tsx";
import * as $$$$$$$$50 from "./sections/Live Projects/Hero.tsx";
import * as $$$$$$$$51 from "./sections/Live Projects/ProjectsGrid.tsx";
import * as $$$$$$$$52 from "./sections/Sidebar.tsx";
import * as $$$$$$$$53 from "./sections/MainBanner.tsx";
import * as $$$$$$$$54 from "./sections/TripletBanner.tsx";
import * as $$$$$$$$55 from "./sections/CampMentor.tsx";
import * as $$$$$$$$56 from "./sections/Thanks.tsx";
import * as $$$$$$$$57 from "./sections/Page.tsx";
import * as $$$$$$$$58 from "./sections/Faq.tsx";
import * as $$$$$$$$59 from "./sections/DepoimentsCarrossel.tsx";
import * as $$$$$$$$60 from "./sections/Links.tsx";
import * as $$$$$$$$61 from "./sections/Hub/Advantage.tsx";
import * as $$$$$$$$62 from "./sections/Hub/SectionSubtitle.tsx";
import * as $$$$$$$$63 from "./sections/Hub/Heading.tsx";
import * as $$$$$$$$64 from "./sections/Hub/TemplatesGrid.tsx";
import * as $$$$$$$$65 from "./sections/Hub/Agencies.tsx";
import * as $$$$$$$$66 from "./sections/Hub/TemplatePreview.tsx";
import * as $$$$$$$$67 from "./sections/Hub/SectionTitle.tsx";
import * as $$$$$$$$68 from "./sections/Hub/TemplateIframe.tsx";
import * as $$$$$$$$69 from "./sections/Hub/Integrations.tsx";
import * as $$$$$$$$70 from "./sections/Hub/Creator.tsx";
import * as $$$$$$$$71 from "./sections/Delight.tsx";
import * as $$$$$$$$72 from "./sections/Benefits.tsx";
import * as $$$$$$$$73 from "./sections/About.tsx";
import * as $$$$$$$$74 from "./sections/HelpFaq.tsx";
import * as $$$$$$$$75 from "./sections/RankingAnalyze.tsx";
import * as $$$$$$$$76 from "./sections/RankingHeader.tsx";
import * as $$$$$$$$77 from "./sections/Carousel.tsx";
import * as $$$$$$$$$0 from "./matchers/MatchPath.ts";
import * as i1$0 from "$live/loaders/secret.ts";
import * as i1$1 from "$live/loaders/state.ts";
import * as i1$2 from "$live/loaders/workflows/events.ts";
import * as i1$3 from "$live/loaders/workflows/get.ts";
import * as i1$$0 from "$live/handlers/devPage.ts";
import * as i1$$1 from "$live/handlers/fresh.ts";
import * as i1$$2 from "$live/handlers/proxy.ts";
import * as i1$$3 from "$live/handlers/redirect.ts";
import * as i1$$4 from "$live/handlers/router.ts";
import * as i1$$5 from "$live/handlers/routesSelection.ts";
import * as i1$$6 from "$live/handlers/workflowRunner.ts";
import * as i1$$$0 from "$live/pages/LivePage.tsx";
import * as i1$$$$0 from "$live/sections/Conditional_Beta.tsx";
import * as i1$$$$1 from "$live/sections/EmptySection.tsx";
import * as i1$$$$2 from "$live/sections/PageInclude.tsx";
import * as i1$$$$3 from "$live/sections/Slot.tsx";
import * as i1$$$$4 from "$live/sections/UseSlot.tsx";
import * as i1$$$$$0 from "$live/matchers/MatchAlways.ts";
import * as i1$$$$$1 from "$live/matchers/MatchCron.ts";
import * as i1$$$$$2 from "$live/matchers/MatchDate.ts";
import * as i1$$$$$3 from "$live/matchers/MatchDevice.ts";
import * as i1$$$$$4 from "$live/matchers/MatchEnvironment.ts";
import * as i1$$$$$5 from "$live/matchers/MatchHost.ts";
import * as i1$$$$$6 from "$live/matchers/MatchLocation.ts";
import * as i1$$$$$7 from "$live/matchers/MatchMulti.ts";
import * as i1$$$$$8 from "$live/matchers/MatchRandom.ts";
import * as i1$$$$$9 from "$live/matchers/MatchSite.ts";
import * as i1$$$$$10 from "$live/matchers/MatchUserAgent.ts";
import * as i1$$$$$$0 from "$live/flags/audience.ts";
import * as i1$$$$$$1 from "$live/flags/everyone.ts";
import * as i1$$$$$$2 from "$live/flags/flag.ts";
import * as i1$$$$$$3 from "$live/flags/multivariate.ts";
import * as i1$$$$$$$0 from "$live/actions/secrets/encrypt.ts";
import * as i1$$$$$$$1 from "$live/actions/workflows/cancel.ts";
import * as i1$$$$$$$2 from "$live/actions/workflows/signal.ts";
import * as i1$$$$$$$3 from "$live/actions/workflows/start.ts";
import * as i2$0 from "deco-sites/std/functions/butterCMSAds.ts";
import * as i2$1 from "deco-sites/std/functions/butterCMSBrands.ts";
import * as i2$2 from "deco-sites/std/functions/butterCMSCategories.ts";
import * as i2$3 from "deco-sites/std/functions/butterCMSFeaturedPosts.ts";
import * as i2$4 from "deco-sites/std/functions/butterCMSPage.ts";
import * as i2$5 from "deco-sites/std/functions/butterCMSPlaces.ts";
import * as i2$6 from "deco-sites/std/functions/butterCMSPostDetail.ts";
import * as i2$7 from "deco-sites/std/functions/butterCMSPosts.ts";
import * as i2$8 from "deco-sites/std/functions/butterCMSRelatedPosts.ts";
import * as i2$9 from "deco-sites/std/functions/occProductDetailsPage.ts";
import * as i2$10 from "deco-sites/std/functions/requestToParam.ts";
import * as i2$11 from "deco-sites/std/functions/shopifyProductDetailsPage.ts";
import * as i2$12 from "deco-sites/std/functions/shopifyProductList.ts";
import * as i2$13 from "deco-sites/std/functions/shopifyProductListingPage.ts";
import * as i2$14 from "deco-sites/std/functions/vndaProductList.ts";
import * as i2$15 from "deco-sites/std/functions/vndaProductListingPage.ts";
import * as i2$16 from "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts";
import * as i2$17 from "deco-sites/std/functions/vtexLegacyProductList.ts";
import * as i2$18 from "deco-sites/std/functions/vtexLegacyProductListingPage.ts";
import * as i2$19 from "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts";
import * as i2$20 from "deco-sites/std/functions/vtexNavbar.ts";
import * as i2$21 from "deco-sites/std/functions/vtexProductDetailsPage.ts";
import * as i2$22 from "deco-sites/std/functions/vtexProductList.ts";
import * as i2$23 from "deco-sites/std/functions/vtexProductListingPage.ts";
import * as i2$24 from "deco-sites/std/functions/vtexSuggestions.ts";
import * as i2$25 from "deco-sites/std/functions/vtexWishlist.ts";
import * as i2$$0 from "deco-sites/std/accounts/butterCMS.ts";
import * as i2$$1 from "deco-sites/std/accounts/linxImpulse.ts";
import * as i2$$2 from "deco-sites/std/accounts/nuvemShop.ts";
import * as i2$$3 from "deco-sites/std/accounts/occ.ts";
import * as i2$$4 from "deco-sites/std/accounts/shopify.ts";
import * as i2$$5 from "deco-sites/std/accounts/vnda.ts";
import * as i2$$6 from "deco-sites/std/accounts/vtex.ts";
import * as i2$$7 from "deco-sites/std/accounts/yourViews.ts";
import * as i2$$$0 from "deco-sites/std/loaders/linxImpulse/autocompletes/popular.ts";
import * as i2$$$1 from "deco-sites/std/loaders/linxImpulse/autocompletes/suggestions.ts";
import * as i2$$$2 from "deco-sites/std/loaders/linxImpulse/pages/recommendations.ts";
import * as i2$$$3 from "deco-sites/std/loaders/linxImpulse/products/similarItems.ts";
import * as i2$$$4 from "deco-sites/std/loaders/linxImpulse/search.ts";
import * as i2$$$5 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductDetailsPage.ts";
import * as i2$$$6 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductList.ts";
import * as i2$$$7 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductListingPage.ts";
import * as i2$$$8 from "deco-sites/std/loaders/vnda/cart.ts";
import * as i2$$$9 from "deco-sites/std/loaders/vnda/productDetailsPage.ts";
import * as i2$$$10 from "deco-sites/std/loaders/vnda/productList.ts";
import * as i2$$$11 from "deco-sites/std/loaders/vnda/productListingPage.ts";
import * as i2$$$12 from "deco-sites/std/loaders/vnda/proxy.ts";
import * as i2$$$13 from "deco-sites/std/loaders/vtex/cart.ts";
import * as i2$$$14 from "deco-sites/std/loaders/vtex/intelligentSearch/productDetailsPage.ts";
import * as i2$$$15 from "deco-sites/std/loaders/vtex/intelligentSearch/productList.ts";
import * as i2$$$16 from "deco-sites/std/loaders/vtex/intelligentSearch/productListingPage.ts";
import * as i2$$$17 from "deco-sites/std/loaders/vtex/intelligentSearch/suggestions.ts";
import * as i2$$$18 from "deco-sites/std/loaders/vtex/legacy/productDetailsPage.ts";
import * as i2$$$19 from "deco-sites/std/loaders/vtex/legacy/productList.ts";
import * as i2$$$20 from "deco-sites/std/loaders/vtex/legacy/productListingPage.ts";
import * as i2$$$21 from "deco-sites/std/loaders/vtex/legacy/relatedProductsLoader.ts";
import * as i2$$$22 from "deco-sites/std/loaders/vtex/legacy/suggestions.ts";
import * as i2$$$23 from "deco-sites/std/loaders/vtex/navbar.ts";
import * as i2$$$24 from "deco-sites/std/loaders/vtex/proxy.ts";
import * as i2$$$25 from "deco-sites/std/loaders/vtex/user.ts";
import * as i2$$$26 from "deco-sites/std/loaders/vtex/wishlist.ts";
import * as i2$$$27 from "deco-sites/std/loaders/x/font.ts";
import * as i2$$$28 from "deco-sites/std/loaders/x/image.ts";
import * as i2$$$29 from "deco-sites/std/loaders/x/redirects.ts";
import * as i2$$$30 from "deco-sites/std/loaders/x/redirectsFromCsv.ts";
import * as i2$$$$0 from "deco-sites/std/handlers/sitemap.ts";
import * as i2$$$$1 from "deco-sites/std/handlers/vtex/sitemap.ts";
import * as i2$$$$$0 from "deco-sites/std/sections/Analytics.tsx";
import * as i2$$$$$1 from "deco-sites/std/sections/configButterCMS.global.tsx";
import * as i2$$$$$2 from "deco-sites/std/sections/configLinxImpulse.global.tsx";
import * as i2$$$$$3 from "deco-sites/std/sections/configNuvemShop.tsx";
import * as i2$$$$$4 from "deco-sites/std/sections/configOCC.global.tsx";
import * as i2$$$$$5 from "deco-sites/std/sections/configShopify.global.tsx";
import * as i2$$$$$6 from "deco-sites/std/sections/configVTEX.global.tsx";
import * as i2$$$$$7 from "deco-sites/std/sections/configYourViews.global.tsx";
import * as i2$$$$$8 from "deco-sites/std/sections/SEO.tsx";
import * as i2$$$$$9 from "deco-sites/std/sections/SEOPDP.tsx";
import * as i2$$$$$10 from "deco-sites/std/sections/SEOPLP.tsx";
import * as i2$$$$$11 from "deco-sites/std/sections/VTEXPortalDataLayerCompatibility.tsx";
import * as i2$$$$$$0 from "deco-sites/std/actions/vnda/cart/addItem.ts";
import * as i2$$$$$$1 from "deco-sites/std/actions/vnda/cart/setShippingAddress.ts";
import * as i2$$$$$$2 from "deco-sites/std/actions/vnda/cart/updateCoupon.ts";
import * as i2$$$$$$3 from "deco-sites/std/actions/vnda/cart/updateItem.ts";
import * as i2$$$$$$4 from "deco-sites/std/actions/vtex/analytics/sendEvent.ts";
import * as i2$$$$$$5 from "deco-sites/std/actions/vtex/cart/addItems.ts";
import * as i2$$$$$$6 from "deco-sites/std/actions/vtex/cart/getInstallment.ts";
import * as i2$$$$$$7 from "deco-sites/std/actions/vtex/cart/removeItemAttachment.ts";
import * as i2$$$$$$8 from "deco-sites/std/actions/vtex/cart/removeItems.ts";
import * as i2$$$$$$9 from "deco-sites/std/actions/vtex/cart/simulation.ts";
import * as i2$$$$$$10 from "deco-sites/std/actions/vtex/cart/updateAttachment.ts";
import * as i2$$$$$$11 from "deco-sites/std/actions/vtex/cart/updateCoupons.ts";
import * as i2$$$$$$12 from "deco-sites/std/actions/vtex/cart/updateItemAttachment.ts";
import * as i2$$$$$$13 from "deco-sites/std/actions/vtex/cart/updateItemPrice.ts";
import * as i2$$$$$$14 from "deco-sites/std/actions/vtex/cart/updateItems.ts";
import * as i2$$$$$$15 from "deco-sites/std/actions/vtex/cart/updateProfile.ts";
import * as i2$$$$$$16 from "deco-sites/std/actions/vtex/cart/updateUser.ts";
import * as i2$$$$$$17 from "deco-sites/std/actions/vtex/newsletter/subscribe.ts";
import * as i2$$$$$$18 from "deco-sites/std/actions/vtex/notifyme.ts";
import * as i2$$$$$$19 from "deco-sites/std/actions/vtex/wishlist/addItem.ts";
import * as i2$$$$$$20 from "deco-sites/std/actions/vtex/wishlist/removeItem.ts";

const manifest = {
  "functions": {
    "deco-sites/starting/functions/LoadGitHubRaw.ts": $1,
    "deco-sites/starting/functions/LoadGitHubRawPost.ts": $0,
    "deco-sites/starting/functions/LoadGitHubRawPostList.ts": $4,
    "deco-sites/starting/functions/LoadPageProps.ts": $3,
    "deco-sites/starting/functions/psiRankingList.ts": $2,
    "deco-sites/std/functions/butterCMSAds.ts": i2$0,
    "deco-sites/std/functions/butterCMSBrands.ts": i2$1,
    "deco-sites/std/functions/butterCMSCategories.ts": i2$2,
    "deco-sites/std/functions/butterCMSFeaturedPosts.ts": i2$3,
    "deco-sites/std/functions/butterCMSPage.ts": i2$4,
    "deco-sites/std/functions/butterCMSPlaces.ts": i2$5,
    "deco-sites/std/functions/butterCMSPostDetail.ts": i2$6,
    "deco-sites/std/functions/butterCMSPosts.ts": i2$7,
    "deco-sites/std/functions/butterCMSRelatedPosts.ts": i2$8,
    "deco-sites/std/functions/occProductDetailsPage.ts": i2$9,
    "deco-sites/std/functions/requestToParam.ts": i2$10,
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": i2$11,
    "deco-sites/std/functions/shopifyProductList.ts": i2$12,
    "deco-sites/std/functions/shopifyProductListingPage.ts": i2$13,
    "deco-sites/std/functions/vndaProductList.ts": i2$14,
    "deco-sites/std/functions/vndaProductListingPage.ts": i2$15,
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": i2$16,
    "deco-sites/std/functions/vtexLegacyProductList.ts": i2$17,
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": i2$18,
    "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts": i2$19,
    "deco-sites/std/functions/vtexNavbar.ts": i2$20,
    "deco-sites/std/functions/vtexProductDetailsPage.ts": i2$21,
    "deco-sites/std/functions/vtexProductList.ts": i2$22,
    "deco-sites/std/functions/vtexProductListingPage.ts": i2$23,
    "deco-sites/std/functions/vtexSuggestions.ts": i2$24,
    "deco-sites/std/functions/vtexWishlist.ts": i2$25,
  },
  "loaders": {
    "$live/loaders/secret.ts": i1$0,
    "$live/loaders/state.ts": i1$1,
    "$live/loaders/workflows/events.ts": i1$2,
    "$live/loaders/workflows/get.ts": i1$3,
    "deco-sites/starting/loaders/blogPostDetailsLoader.ts": $$$2,
    "deco-sites/starting/loaders/blogPostLoader.ts": $$$1,
    "deco-sites/starting/loaders/blogPostMarkdownLoader.ts": $$$4,
    "deco-sites/starting/loaders/denoLoader.ts": $$$5,
    "deco-sites/starting/loaders/denoTopicsLoader.ts": $$$0,
    "deco-sites/starting/loaders/featuredPosts.ts": $$$3,
    "deco-sites/std/loaders/linxImpulse/autocompletes/popular.ts": i2$$$0,
    "deco-sites/std/loaders/linxImpulse/autocompletes/suggestions.ts": i2$$$1,
    "deco-sites/std/loaders/linxImpulse/pages/recommendations.ts": i2$$$2,
    "deco-sites/std/loaders/linxImpulse/products/similarItems.ts": i2$$$3,
    "deco-sites/std/loaders/linxImpulse/search.ts": i2$$$4,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductDetailsPage.ts": i2$$$5,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductList.ts": i2$$$6,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductListingPage.ts": i2$$$7,
    "deco-sites/std/loaders/vnda/cart.ts": i2$$$8,
    "deco-sites/std/loaders/vnda/productDetailsPage.ts": i2$$$9,
    "deco-sites/std/loaders/vnda/productList.ts": i2$$$10,
    "deco-sites/std/loaders/vnda/productListingPage.ts": i2$$$11,
    "deco-sites/std/loaders/vnda/proxy.ts": i2$$$12,
    "deco-sites/std/loaders/vtex/cart.ts": i2$$$13,
    "deco-sites/std/loaders/vtex/intelligentSearch/productDetailsPage.ts":
      i2$$$14,
    "deco-sites/std/loaders/vtex/intelligentSearch/productList.ts": i2$$$15,
    "deco-sites/std/loaders/vtex/intelligentSearch/productListingPage.ts":
      i2$$$16,
    "deco-sites/std/loaders/vtex/intelligentSearch/suggestions.ts": i2$$$17,
    "deco-sites/std/loaders/vtex/legacy/productDetailsPage.ts": i2$$$18,
    "deco-sites/std/loaders/vtex/legacy/productList.ts": i2$$$19,
    "deco-sites/std/loaders/vtex/legacy/productListingPage.ts": i2$$$20,
    "deco-sites/std/loaders/vtex/legacy/relatedProductsLoader.ts": i2$$$21,
    "deco-sites/std/loaders/vtex/legacy/suggestions.ts": i2$$$22,
    "deco-sites/std/loaders/vtex/navbar.ts": i2$$$23,
    "deco-sites/std/loaders/vtex/proxy.ts": i2$$$24,
    "deco-sites/std/loaders/vtex/user.ts": i2$$$25,
    "deco-sites/std/loaders/vtex/wishlist.ts": i2$$$26,
    "deco-sites/std/loaders/x/font.ts": i2$$$27,
    "deco-sites/std/loaders/x/image.ts": i2$$$28,
    "deco-sites/std/loaders/x/redirects.ts": i2$$$29,
    "deco-sites/std/loaders/x/redirectsFromCsv.ts": i2$$$30,
  },
  "routes": {
    "./routes/_app.tsx": $$$$12,
    "./routes/_middleware.ts": $$$$5,
    "./routes/admin/[...catchall].tsx": $$$$3,
    "./routes/api/calc.tsx": $$$$10,
    "./routes/api/case.tsx": $$$$7,
    "./routes/api/leads.tsx": $$$$11,
    "./routes/api/ranking.ts": $$$$9,
    "./routes/api/webinar.tsx": $$$$8,
    "./routes/docs/[...slug].tsx": $$$$6,
    "./routes/gfm.css.ts": $$$$1,
    "./routes/hackathon4.ts": $$$$4,
    "./routes/index.tsx": $$$$0,
    "./routes/proxy/image/index.tsx": $$$$2,
  },
  "islands": {
    "./islands/CampHeader.tsx": $$$$$5,
    "./islands/CampMentor.tsx": $$$$$15,
    "./islands/Case.tsx": $$$$$1,
    "./islands/ChangeDevice.tsx": $$$$$12,
    "./islands/ChangeTheme.tsx": $$$$$7,
    "./islands/Cms.tsx": $$$$$8,
    "./islands/ContactUs.tsx": $$$$$10,
    "./islands/Content.tsx": $$$$$4,
    "./islands/FaviconImage.tsx": $$$$$2,
    "./islands/Header.tsx": $$$$$13,
    "./islands/HelpFaq.tsx": $$$$$16,
    "./islands/ImpactCalculator.tsx": $$$$$3,
    "./islands/LiveProjects.tsx": $$$$$6,
    "./islands/OnThisPage.tsx": $$$$$0,
    "./islands/PopularDocuments.tsx": $$$$$9,
    "./islands/RankingAnalyze.tsx": $$$$$17,
    "./islands/RankingHeader.tsx": $$$$$18,
    "./islands/Sidebar.tsx": $$$$$14,
    "./islands/SliderJS.tsx": $$$$$11,
  },
  "sections": {
    "$live/sections/Conditional_Beta.tsx": i1$$$$0,
    "$live/sections/EmptySection.tsx": i1$$$$1,
    "$live/sections/PageInclude.tsx": i1$$$$2,
    "$live/sections/Slot.tsx": i1$$$$3,
    "$live/sections/UseSlot.tsx": i1$$$$4,
    "deco-sites/starting/sections/About.tsx": $$$$$$$$73,
    "deco-sites/starting/sections/Benefits.tsx": $$$$$$$$72,
    "deco-sites/starting/sections/BlogHeader.tsx": $$$$$$$$9,
    "deco-sites/starting/sections/BlogPostHeader.tsx": $$$$$$$$20,
    "deco-sites/starting/sections/BlogPostList.tsx": $$$$$$$$16,
    "deco-sites/starting/sections/BlogPostSEO.tsx": $$$$$$$$38,
    "deco-sites/starting/sections/CampComments.tsx": $$$$$$$$8,
    "deco-sites/starting/sections/CampHero.tsx": $$$$$$$$1,
    "deco-sites/starting/sections/CampMentor.tsx": $$$$$$$$55,
    "deco-sites/starting/sections/CampRegistration.tsx": $$$$$$$$27,
    "deco-sites/starting/sections/CampSteps.tsx": $$$$$$$$22,
    "deco-sites/starting/sections/Carousel.tsx": $$$$$$$$77,
    "deco-sites/starting/sections/Case/ArticleBannerCTA.tsx": $$$$$$$$43,
    "deco-sites/starting/sections/Case/ArticleDivider.tsx": $$$$$$$$48,
    "deco-sites/starting/sections/Case/ArticleHeader.tsx": $$$$$$$$44,
    "deco-sites/starting/sections/Case/ArticleNumbers.tsx": $$$$$$$$49,
    "deco-sites/starting/sections/Case/ArticleParagraph.tsx": $$$$$$$$47,
    "deco-sites/starting/sections/Case/ArticleQuote.tsx": $$$$$$$$45,
    "deco-sites/starting/sections/Case/ArticleVideo.tsx": $$$$$$$$46,
    "deco-sites/starting/sections/Case/ArticleYoutubeVideo.tsx": $$$$$$$$41,
    "deco-sites/starting/sections/Case/Case.tsx": $$$$$$$$42,
    "deco-sites/starting/sections/Cms.tsx": $$$$$$$$32,
    "deco-sites/starting/sections/Community.tsx": $$$$$$$$28,
    "deco-sites/starting/sections/ContactUs.tsx": $$$$$$$$37,
    "deco-sites/starting/sections/Content.tsx": $$$$$$$$25,
    "deco-sites/starting/sections/Delight.tsx": $$$$$$$$71,
    "deco-sites/starting/sections/DepoimentsCarrossel.tsx": $$$$$$$$59,
    "deco-sites/starting/sections/Differentials.tsx": $$$$$$$$31,
    "deco-sites/starting/sections/Divider.tsx": $$$$$$$$29,
    "deco-sites/starting/sections/Faq.tsx": $$$$$$$$58,
    "deco-sites/starting/sections/Features.tsx": $$$$$$$$21,
    "deco-sites/starting/sections/Footer.tsx": $$$$$$$$33,
    "deco-sites/starting/sections/FooterBigLogo.tsx": $$$$$$$$39,
    "deco-sites/starting/sections/General/Spacer.tsx": $$$$$$$$24,
    "deco-sites/starting/sections/Head.tsx": $$$$$$$$34,
    "deco-sites/starting/sections/Header.tsx": $$$$$$$$40,
    "deco-sites/starting/sections/HelpBlogPosts.tsx": $$$$$$$$26,
    "deco-sites/starting/sections/HelpFaq.tsx": $$$$$$$$74,
    "deco-sites/starting/sections/HeroPost.tsx": $$$$$$$$5,
    "deco-sites/starting/sections/Home/Brands.tsx": $$$$$$$$6,
    "deco-sites/starting/sections/HowCanWeHelp.tsx": $$$$$$$$13,
    "deco-sites/starting/sections/Hub/Advantage.tsx": $$$$$$$$61,
    "deco-sites/starting/sections/Hub/Agencies.tsx": $$$$$$$$65,
    "deco-sites/starting/sections/Hub/Creator.tsx": $$$$$$$$70,
    "deco-sites/starting/sections/Hub/Heading.tsx": $$$$$$$$63,
    "deco-sites/starting/sections/Hub/Integrations.tsx": $$$$$$$$69,
    "deco-sites/starting/sections/Hub/SectionSubtitle.tsx": $$$$$$$$62,
    "deco-sites/starting/sections/Hub/SectionTitle.tsx": $$$$$$$$67,
    "deco-sites/starting/sections/Hub/TemplateIframe.tsx": $$$$$$$$68,
    "deco-sites/starting/sections/Hub/TemplatePreview.tsx": $$$$$$$$66,
    "deco-sites/starting/sections/Hub/TemplatesGrid.tsx": $$$$$$$$64,
    "deco-sites/starting/sections/ImpactCalculator.tsx": $$$$$$$$19,
    "deco-sites/starting/sections/Integration.tsx": $$$$$$$$36,
    "deco-sites/starting/sections/JoinOurCommunity.tsx": $$$$$$$$17,
    "deco-sites/starting/sections/Links.tsx": $$$$$$$$60,
    "deco-sites/starting/sections/Live Projects/Hero.tsx": $$$$$$$$50,
    "deco-sites/starting/sections/Live Projects/ProjectsGrid.tsx": $$$$$$$$51,
    "deco-sites/starting/sections/MainBanner.tsx": $$$$$$$$53,
    "deco-sites/starting/sections/Markdown.tsx": $$$$$$$$23,
    "deco-sites/starting/sections/MarkdownContent.tsx": $$$$$$$$2,
    "deco-sites/starting/sections/OnThisPage.tsx": $$$$$$$$3,
    "deco-sites/starting/sections/Page.tsx": $$$$$$$$57,
    "deco-sites/starting/sections/Partner.tsx": $$$$$$$$30,
    "deco-sites/starting/sections/PopularDocuments.tsx": $$$$$$$$35,
    "deco-sites/starting/sections/PopularTopics.tsx": $$$$$$$$0,
    "deco-sites/starting/sections/Pricing.tsx": $$$$$$$$11,
    "deco-sites/starting/sections/PricingValue.tsx": $$$$$$$$18,
    "deco-sites/starting/sections/QuillText.tsx": $$$$$$$$4,
    "deco-sites/starting/sections/RankingAnalyze.tsx": $$$$$$$$75,
    "deco-sites/starting/sections/RankingHeader.tsx": $$$$$$$$76,
    "deco-sites/starting/sections/RankingList.tsx": $$$$$$$$10,
    "deco-sites/starting/sections/SectionList.tsx": $$$$$$$$12,
    "deco-sites/starting/sections/Sidebar.tsx": $$$$$$$$52,
    "deco-sites/starting/sections/StripePricing.tsx": $$$$$$$$7,
    "deco-sites/starting/sections/Thanks.tsx": $$$$$$$$56,
    "deco-sites/starting/sections/TripletBanner.tsx": $$$$$$$$54,
    "deco-sites/starting/sections/Webinar/Content.tsx": $$$$$$$$15,
    "deco-sites/starting/sections/Webinar/Hero.tsx": $$$$$$$$14,
    "deco-sites/std/sections/Analytics.tsx": i2$$$$$0,
    "deco-sites/std/sections/configButterCMS.global.tsx": i2$$$$$1,
    "deco-sites/std/sections/configLinxImpulse.global.tsx": i2$$$$$2,
    "deco-sites/std/sections/configNuvemShop.tsx": i2$$$$$3,
    "deco-sites/std/sections/configOCC.global.tsx": i2$$$$$4,
    "deco-sites/std/sections/configShopify.global.tsx": i2$$$$$5,
    "deco-sites/std/sections/configVTEX.global.tsx": i2$$$$$6,
    "deco-sites/std/sections/configYourViews.global.tsx": i2$$$$$7,
    "deco-sites/std/sections/SEO.tsx": i2$$$$$8,
    "deco-sites/std/sections/SEOPDP.tsx": i2$$$$$9,
    "deco-sites/std/sections/SEOPLP.tsx": i2$$$$$10,
    "deco-sites/std/sections/VTEXPortalDataLayerCompatibility.tsx": i2$$$$$11,
  },
  "matchers": {
    "$live/matchers/MatchAlways.ts": i1$$$$$0,
    "$live/matchers/MatchCron.ts": i1$$$$$1,
    "$live/matchers/MatchDate.ts": i1$$$$$2,
    "$live/matchers/MatchDevice.ts": i1$$$$$3,
    "$live/matchers/MatchEnvironment.ts": i1$$$$$4,
    "$live/matchers/MatchHost.ts": i1$$$$$5,
    "$live/matchers/MatchLocation.ts": i1$$$$$6,
    "$live/matchers/MatchMulti.ts": i1$$$$$7,
    "$live/matchers/MatchRandom.ts": i1$$$$$8,
    "$live/matchers/MatchSite.ts": i1$$$$$9,
    "$live/matchers/MatchUserAgent.ts": i1$$$$$10,
    "deco-sites/starting/matchers/MatchPath.ts": $$$$$$$$$0,
  },
  "name": "deco-sites/starting",
  "handlers": {
    "$live/handlers/devPage.ts": i1$$0,
    "$live/handlers/fresh.ts": i1$$1,
    "$live/handlers/proxy.ts": i1$$2,
    "$live/handlers/redirect.ts": i1$$3,
    "$live/handlers/router.ts": i1$$4,
    "$live/handlers/routesSelection.ts": i1$$5,
    "$live/handlers/workflowRunner.ts": i1$$6,
    "deco-sites/std/handlers/sitemap.ts": i2$$$$0,
    "deco-sites/std/handlers/vtex/sitemap.ts": i2$$$$1,
  },
  "pages": {
    "$live/pages/LivePage.tsx": i1$$$0,
  },
  "flags": {
    "$live/flags/audience.ts": i1$$$$$$0,
    "$live/flags/everyone.ts": i1$$$$$$1,
    "$live/flags/flag.ts": i1$$$$$$2,
    "$live/flags/multivariate.ts": i1$$$$$$3,
  },
  "actions": {
    "$live/actions/secrets/encrypt.ts": i1$$$$$$$0,
    "$live/actions/workflows/cancel.ts": i1$$$$$$$1,
    "$live/actions/workflows/signal.ts": i1$$$$$$$2,
    "$live/actions/workflows/start.ts": i1$$$$$$$3,
    "deco-sites/std/actions/vnda/cart/addItem.ts": i2$$$$$$0,
    "deco-sites/std/actions/vnda/cart/setShippingAddress.ts": i2$$$$$$1,
    "deco-sites/std/actions/vnda/cart/updateCoupon.ts": i2$$$$$$2,
    "deco-sites/std/actions/vnda/cart/updateItem.ts": i2$$$$$$3,
    "deco-sites/std/actions/vtex/analytics/sendEvent.ts": i2$$$$$$4,
    "deco-sites/std/actions/vtex/cart/addItems.ts": i2$$$$$$5,
    "deco-sites/std/actions/vtex/cart/getInstallment.ts": i2$$$$$$6,
    "deco-sites/std/actions/vtex/cart/removeItemAttachment.ts": i2$$$$$$7,
    "deco-sites/std/actions/vtex/cart/removeItems.ts": i2$$$$$$8,
    "deco-sites/std/actions/vtex/cart/simulation.ts": i2$$$$$$9,
    "deco-sites/std/actions/vtex/cart/updateAttachment.ts": i2$$$$$$10,
    "deco-sites/std/actions/vtex/cart/updateCoupons.ts": i2$$$$$$11,
    "deco-sites/std/actions/vtex/cart/updateItemAttachment.ts": i2$$$$$$12,
    "deco-sites/std/actions/vtex/cart/updateItemPrice.ts": i2$$$$$$13,
    "deco-sites/std/actions/vtex/cart/updateItems.ts": i2$$$$$$14,
    "deco-sites/std/actions/vtex/cart/updateProfile.ts": i2$$$$$$15,
    "deco-sites/std/actions/vtex/cart/updateUser.ts": i2$$$$$$16,
    "deco-sites/std/actions/vtex/newsletter/subscribe.ts": i2$$$$$$17,
    "deco-sites/std/actions/vtex/notifyme.ts": i2$$$$$$18,
    "deco-sites/std/actions/vtex/wishlist/addItem.ts": i2$$$$$$19,
    "deco-sites/std/actions/vtex/wishlist/removeItem.ts": i2$$$$$$20,
  },
  "accounts": {
    "deco-sites/std/accounts/butterCMS.ts": i2$$0,
    "deco-sites/std/accounts/linxImpulse.ts": i2$$1,
    "deco-sites/std/accounts/nuvemShop.ts": i2$$2,
    "deco-sites/std/accounts/occ.ts": i2$$3,
    "deco-sites/std/accounts/shopify.ts": i2$$4,
    "deco-sites/std/accounts/vnda.ts": i2$$5,
    "deco-sites/std/accounts/vtex.ts": i2$$6,
    "deco-sites/std/accounts/yourViews.ts": i2$$7,
  },
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
