// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./functions/LoadGitHubRaw.ts";
import * as $1 from "./functions/LoadGitHubRawPost.ts";
import * as $2 from "./functions/LoadGitHubRawPostList.ts";
import * as $3 from "./functions/LoadPageProps.ts";
import * as $4 from "./functions/psiRankingList.ts";
import * as $$$0 from "./loaders/blogPostDetailsLoader.ts";
import * as $$$1 from "./loaders/blogPostLoader.ts";
import * as $$$2 from "./loaders/blogPostMarkdownLoader.ts";
import * as $$$3 from "./loaders/denoLoader.ts";
import * as $$$4 from "./loaders/denoTopicsLoader.ts";
import * as $$$5 from "./loaders/featuredPosts.ts";
import * as $$$$0 from "./handlers/feed.ts";
import * as $$$$$$0 from "./sections/About.tsx";
import * as $$$$$$1 from "./sections/Benefits.tsx";
import * as $$$$$$2 from "./sections/BlogHeader.tsx";
import * as $$$$$$3 from "./sections/BlogPostHeader.tsx";
import * as $$$$$$4 from "./sections/BlogPostList.tsx";
import * as $$$$$$5 from "./sections/BlogPostSEO.tsx";
import * as $$$$$$6 from "./sections/CampComments.tsx";
import * as $$$$$$7 from "./sections/CampHero.tsx";
import * as $$$$$$8 from "./sections/CampMentor.tsx";
import * as $$$$$$9 from "./sections/CampRegistration.tsx";
import * as $$$$$$10 from "./sections/CampSteps.tsx";
import * as $$$$$$11 from "./sections/Carousel.tsx";
import * as $$$$$$12 from "./sections/Case/ArticleBannerCTA.tsx";
import * as $$$$$$13 from "./sections/Case/ArticleDivider.tsx";
import * as $$$$$$14 from "./sections/Case/ArticleHeader.tsx";
import * as $$$$$$15 from "./sections/Case/ArticleNumbers.tsx";
import * as $$$$$$16 from "./sections/Case/ArticleParagraph.tsx";
import * as $$$$$$17 from "./sections/Case/ArticleQuote.tsx";
import * as $$$$$$18 from "./sections/Case/ArticleVideo.tsx";
import * as $$$$$$19 from "./sections/Case/ArticleYoutubeVideo.tsx";
import * as $$$$$$20 from "./sections/Case/Case.tsx";
import * as $$$$$$21 from "./sections/Cms.tsx";
import * as $$$$$$22 from "./sections/Community.tsx";
import * as $$$$$$23 from "./sections/ContactUs.tsx";
import * as $$$$$$24 from "./sections/Content.tsx";
import * as $$$$$$25 from "./sections/CustomizableContent.tsx";
import * as $$$$$$26 from "./sections/Delight.tsx";
import * as $$$$$$27 from "./sections/DepoimentsCarrossel.tsx";
import * as $$$$$$28 from "./sections/Differentials.tsx";
import * as $$$$$$29 from "./sections/Divider.tsx";
import * as $$$$$$30 from "./sections/Faq.tsx";
import * as $$$$$$31 from "./sections/Features.tsx";
import * as $$$$$$32 from "./sections/Footer.tsx";
import * as $$$$$$33 from "./sections/FooterBigLogo.tsx";
import * as $$$$$$34 from "./sections/General/Spacer.tsx";
import * as $$$$$$35 from "./sections/Head.tsx";
import * as $$$$$$36 from "./sections/Header.tsx";
import * as $$$$$$37 from "./sections/HelpBlogPosts.tsx";
import * as $$$$$$38 from "./sections/HelpFaq.tsx";
import * as $$$$$$39 from "./sections/HeroPost.tsx";
import * as $$$$$$40 from "./sections/Home/Brands.tsx";
import * as $$$$$$41 from "./sections/HowCanWeHelp.tsx";
import * as $$$$$$42 from "./sections/Hub/Advantage.tsx";
import * as $$$$$$43 from "./sections/Hub/Agencies.tsx";
import * as $$$$$$44 from "./sections/Hub/Creator.tsx";
import * as $$$$$$45 from "./sections/Hub/Heading.tsx";
import * as $$$$$$46 from "./sections/Hub/Integrations.tsx";
import * as $$$$$$47 from "./sections/Hub/SectionSubtitle.tsx";
import * as $$$$$$48 from "./sections/Hub/SectionTitle.tsx";
import * as $$$$$$49 from "./sections/Hub/TemplateIframe.tsx";
import * as $$$$$$50 from "./sections/Hub/TemplatePreview.tsx";
import * as $$$$$$51 from "./sections/Hub/TemplatesGrid.tsx";
import * as $$$$$$52 from "./sections/ImpactCalculator.tsx";
import * as $$$$$$53 from "./sections/Integration.tsx";
import * as $$$$$$54 from "./sections/JoinOurCommunity.tsx";
import * as $$$$$$55 from "./sections/Links.tsx";
import * as $$$$$$56 from "./sections/Live Projects/Hero.tsx";
import * as $$$$$$57 from "./sections/Live Projects/ProjectsGrid.tsx";
import * as $$$$$$58 from "./sections/MainBanner.tsx";
import * as $$$$$$59 from "./sections/Markdown.tsx";
import * as $$$$$$60 from "./sections/MarkdownContent.tsx";
import * as $$$$$$61 from "./sections/OnThisPage.tsx";
import * as $$$$$$62 from "./sections/Page.tsx";
import * as $$$$$$63 from "./sections/Partner.tsx";
import * as $$$$$$64 from "./sections/PopularDocuments.tsx";
import * as $$$$$$65 from "./sections/PopularTopics.tsx";
import * as $$$$$$66 from "./sections/Pricing.tsx";
import * as $$$$$$67 from "./sections/PricingValue.tsx";
import * as $$$$$$68 from "./sections/QuillText.tsx";
import * as $$$$$$69 from "./sections/RankingAnalyze.tsx";
import * as $$$$$$70 from "./sections/RankingHeader.tsx";
import * as $$$$$$71 from "./sections/RankingList.tsx";
import * as $$$$$$72 from "./sections/SectionList.tsx";
import * as $$$$$$73 from "./sections/Sidebar.tsx";
import * as $$$$$$74 from "./sections/StripePricing.tsx";
import * as $$$$$$75 from "./sections/Thanks.tsx";
import * as $$$$$$76 from "./sections/TripletBanner.tsx";
import * as $$$$$$77 from "./sections/Webinar/Content.tsx";
import * as $$$$$$78 from "./sections/Webinar/Hero.tsx";
import * as $$$$$$$0 from "./matchers/MatchPath.ts";
import * as $$$$$$$$$0 from "./actions/startAlgoliaCrawler.ts";
import * as $$$$$$$$$$$0 from "./apps/site.ts";

const manifest = {
  "functions": {
    "deco-sites/starting/functions/LoadGitHubRaw.ts": $0,
    "deco-sites/starting/functions/LoadGitHubRawPost.ts": $1,
    "deco-sites/starting/functions/LoadGitHubRawPostList.ts": $2,
    "deco-sites/starting/functions/LoadPageProps.ts": $3,
    "deco-sites/starting/functions/psiRankingList.ts": $4,
  },
  "loaders": {
    "deco-sites/starting/loaders/blogPostDetailsLoader.ts": $$$0,
    "deco-sites/starting/loaders/blogPostLoader.ts": $$$1,
    "deco-sites/starting/loaders/blogPostMarkdownLoader.ts": $$$2,
    "deco-sites/starting/loaders/denoLoader.ts": $$$3,
    "deco-sites/starting/loaders/denoTopicsLoader.ts": $$$4,
    "deco-sites/starting/loaders/featuredPosts.ts": $$$5,
  },
  "handlers": {
    "deco-sites/starting/handlers/feed.ts": $$$$0,
  },
  "sections": {
    "deco-sites/starting/sections/About.tsx": $$$$$$0,
    "deco-sites/starting/sections/Benefits.tsx": $$$$$$1,
    "deco-sites/starting/sections/BlogHeader.tsx": $$$$$$2,
    "deco-sites/starting/sections/BlogPostHeader.tsx": $$$$$$3,
    "deco-sites/starting/sections/BlogPostList.tsx": $$$$$$4,
    "deco-sites/starting/sections/BlogPostSEO.tsx": $$$$$$5,
    "deco-sites/starting/sections/CampComments.tsx": $$$$$$6,
    "deco-sites/starting/sections/CampHero.tsx": $$$$$$7,
    "deco-sites/starting/sections/CampMentor.tsx": $$$$$$8,
    "deco-sites/starting/sections/CampRegistration.tsx": $$$$$$9,
    "deco-sites/starting/sections/CampSteps.tsx": $$$$$$10,
    "deco-sites/starting/sections/Carousel.tsx": $$$$$$11,
    "deco-sites/starting/sections/Case/ArticleBannerCTA.tsx": $$$$$$12,
    "deco-sites/starting/sections/Case/ArticleDivider.tsx": $$$$$$13,
    "deco-sites/starting/sections/Case/ArticleHeader.tsx": $$$$$$14,
    "deco-sites/starting/sections/Case/ArticleNumbers.tsx": $$$$$$15,
    "deco-sites/starting/sections/Case/ArticleParagraph.tsx": $$$$$$16,
    "deco-sites/starting/sections/Case/ArticleQuote.tsx": $$$$$$17,
    "deco-sites/starting/sections/Case/ArticleVideo.tsx": $$$$$$18,
    "deco-sites/starting/sections/Case/ArticleYoutubeVideo.tsx": $$$$$$19,
    "deco-sites/starting/sections/Case/Case.tsx": $$$$$$20,
    "deco-sites/starting/sections/Cms.tsx": $$$$$$21,
    "deco-sites/starting/sections/Community.tsx": $$$$$$22,
    "deco-sites/starting/sections/ContactUs.tsx": $$$$$$23,
    "deco-sites/starting/sections/Content.tsx": $$$$$$24,
    "deco-sites/starting/sections/CustomizableContent.tsx": $$$$$$25,
    "deco-sites/starting/sections/Delight.tsx": $$$$$$26,
    "deco-sites/starting/sections/DepoimentsCarrossel.tsx": $$$$$$27,
    "deco-sites/starting/sections/Differentials.tsx": $$$$$$28,
    "deco-sites/starting/sections/Divider.tsx": $$$$$$29,
    "deco-sites/starting/sections/Faq.tsx": $$$$$$30,
    "deco-sites/starting/sections/Features.tsx": $$$$$$31,
    "deco-sites/starting/sections/Footer.tsx": $$$$$$32,
    "deco-sites/starting/sections/FooterBigLogo.tsx": $$$$$$33,
    "deco-sites/starting/sections/General/Spacer.tsx": $$$$$$34,
    "deco-sites/starting/sections/Head.tsx": $$$$$$35,
    "deco-sites/starting/sections/Header.tsx": $$$$$$36,
    "deco-sites/starting/sections/HelpBlogPosts.tsx": $$$$$$37,
    "deco-sites/starting/sections/HelpFaq.tsx": $$$$$$38,
    "deco-sites/starting/sections/HeroPost.tsx": $$$$$$39,
    "deco-sites/starting/sections/Home/Brands.tsx": $$$$$$40,
    "deco-sites/starting/sections/HowCanWeHelp.tsx": $$$$$$41,
    "deco-sites/starting/sections/Hub/Advantage.tsx": $$$$$$42,
    "deco-sites/starting/sections/Hub/Agencies.tsx": $$$$$$43,
    "deco-sites/starting/sections/Hub/Creator.tsx": $$$$$$44,
    "deco-sites/starting/sections/Hub/Heading.tsx": $$$$$$45,
    "deco-sites/starting/sections/Hub/Integrations.tsx": $$$$$$46,
    "deco-sites/starting/sections/Hub/SectionSubtitle.tsx": $$$$$$47,
    "deco-sites/starting/sections/Hub/SectionTitle.tsx": $$$$$$48,
    "deco-sites/starting/sections/Hub/TemplateIframe.tsx": $$$$$$49,
    "deco-sites/starting/sections/Hub/TemplatePreview.tsx": $$$$$$50,
    "deco-sites/starting/sections/Hub/TemplatesGrid.tsx": $$$$$$51,
    "deco-sites/starting/sections/ImpactCalculator.tsx": $$$$$$52,
    "deco-sites/starting/sections/Integration.tsx": $$$$$$53,
    "deco-sites/starting/sections/JoinOurCommunity.tsx": $$$$$$54,
    "deco-sites/starting/sections/Links.tsx": $$$$$$55,
    "deco-sites/starting/sections/Live Projects/Hero.tsx": $$$$$$56,
    "deco-sites/starting/sections/Live Projects/ProjectsGrid.tsx": $$$$$$57,
    "deco-sites/starting/sections/MainBanner.tsx": $$$$$$58,
    "deco-sites/starting/sections/Markdown.tsx": $$$$$$59,
    "deco-sites/starting/sections/MarkdownContent.tsx": $$$$$$60,
    "deco-sites/starting/sections/OnThisPage.tsx": $$$$$$61,
    "deco-sites/starting/sections/Page.tsx": $$$$$$62,
    "deco-sites/starting/sections/Partner.tsx": $$$$$$63,
    "deco-sites/starting/sections/PopularDocuments.tsx": $$$$$$64,
    "deco-sites/starting/sections/PopularTopics.tsx": $$$$$$65,
    "deco-sites/starting/sections/Pricing.tsx": $$$$$$66,
    "deco-sites/starting/sections/PricingValue.tsx": $$$$$$67,
    "deco-sites/starting/sections/QuillText.tsx": $$$$$$68,
    "deco-sites/starting/sections/RankingAnalyze.tsx": $$$$$$69,
    "deco-sites/starting/sections/RankingHeader.tsx": $$$$$$70,
    "deco-sites/starting/sections/RankingList.tsx": $$$$$$71,
    "deco-sites/starting/sections/SectionList.tsx": $$$$$$72,
    "deco-sites/starting/sections/Sidebar.tsx": $$$$$$73,
    "deco-sites/starting/sections/StripePricing.tsx": $$$$$$74,
    "deco-sites/starting/sections/Thanks.tsx": $$$$$$75,
    "deco-sites/starting/sections/TripletBanner.tsx": $$$$$$76,
    "deco-sites/starting/sections/Webinar/Content.tsx": $$$$$$77,
    "deco-sites/starting/sections/Webinar/Hero.tsx": $$$$$$78,
  },
  "matchers": {
    "deco-sites/starting/matchers/MatchPath.ts": $$$$$$$0,
  },
  "actions": {
    "deco-sites/starting/actions/startAlgoliaCrawler.ts": $$$$$$$$$0,
  },
  "apps": {
    "deco-sites/starting/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "deco-sites/starting",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
