// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./functions/LoadGitHubRawPostList.ts";
import * as $1 from "./functions/LoadPageProps.ts";
import * as $2 from "./functions/LoadGitHubRaw.ts";
import * as $3 from "./functions/psiRankingList.ts";
import * as $4 from "./functions/LoadGitHubRawPost.ts";
import * as $$$0 from "./loaders/denoLoader.ts";
import * as $$$1 from "./loaders/blogPostDetailsLoader.ts";
import * as $$$2 from "./loaders/denoTopicsLoader.ts";
import * as $$$3 from "./loaders/featuredPosts.ts";
import * as $$$4 from "./loaders/blogPostLoader.ts";
import * as $$$5 from "./loaders/blogPostMarkdownLoader.ts";
import * as $$$$0 from "./handlers/feed.ts";
import * as $$$$$$0 from "./sections/RankingAnalyze.tsx";
import * as $$$$$$1 from "./sections/CustomizableContent.tsx";
import * as $$$$$$2 from "./sections/Links.tsx";
import * as $$$$$$3 from "./sections/PopularDocuments.tsx";
import * as $$$$$$4 from "./sections/BlogPostList.tsx";
import * as $$$$$$5 from "./sections/Integration.tsx";
import * as $$$$$$6 from "./sections/Delight.tsx";
import * as $$$$$$7 from "./sections/SectionList.tsx";
import * as $$$$$$8 from "./sections/BlogHeader.tsx";
import * as $$$$$$9 from "./sections/QuillText.tsx";
import * as $$$$$$10 from "./sections/About.tsx";
import * as $$$$$$11 from "./sections/Camp/Gallery.tsx";
import * as $$$$$$12 from "./sections/Camp/Hero/Hero.tsx";
import * as $$$$$$13 from "./sections/Camp/Images/Carousel.tsx";
import * as $$$$$$14 from "./sections/Camp/Problem/Problem.tsx";
import * as $$$$$$15 from "./sections/Camp/Theme/Theme.tsx";
import * as $$$$$$16 from "./sections/Camp/FAQ/Faq.tsx";
import * as $$$$$$17 from "./sections/Camp/Achievements/Achievements.tsx";
import * as $$$$$$18 from "./sections/Camp/Mentors/Mentors.tsx";
import * as $$$$$$19 from "./sections/Camp/Prices/Prices.tsx";
import * as $$$$$$20 from "./sections/Camp/DndButtons.tsx";
import * as $$$$$$21 from "./sections/Camp/Syllabus/Syllabus.tsx";
import * as $$$$$$22 from "./sections/Camp/Benefits/HowItWorks.tsx";
import * as $$$$$$23 from "./sections/Camp/Benefits/Benefits.tsx";
import * as $$$$$$24 from "./sections/Differentials.tsx";
import * as $$$$$$25 from "./sections/NRF/ImageSection.tsx";
import * as $$$$$$26 from "./sections/NRF/BlogPosts.tsx";
import * as $$$$$$27 from "./sections/NRF/EditorMobile.tsx";
import * as $$$$$$28 from "./sections/NRF/PageWrapper.tsx";
import * as $$$$$$29 from "./sections/NRF/Grid.tsx";
import * as $$$$$$30 from "./sections/NRF/Contact.tsx";
import * as $$$$$$31 from "./sections/NRF/Editor.tsx";
import * as $$$$$$32 from "./sections/NRF/CallToAction.tsx";
import * as $$$$$$33 from "./sections/NRF/PricingValue.tsx";
import * as $$$$$$34 from "./sections/NRF/TextLines.tsx";
import * as $$$$$$35 from "./sections/NRF/DecoFooter.tsx";
import * as $$$$$$36 from "./sections/NRF/Thanks.tsx";
import * as $$$$$$37 from "./sections/NRF/FeaturesWithImage.tsx";
import * as $$$$$$38 from "./sections/NRF/Header.tsx";
import * as $$$$$$39 from "./sections/NRF/HeroFlat.tsx";
import * as $$$$$$40 from "./sections/NRF/PlatformContact.tsx";
import * as $$$$$$41 from "./sections/NRF/Features.tsx";
import * as $$$$$$42 from "./sections/NRF/Questions.tsx";
import * as $$$$$$43 from "./sections/NRF/Pricing.tsx";
import * as $$$$$$44 from "./sections/NRF/Hero.tsx";
import * as $$$$$$45 from "./sections/NRF/Brands.tsx";
import * as $$$$$$46 from "./sections/TripletBanner.tsx";
import * as $$$$$$47 from "./sections/CampRegistration.tsx";
import * as $$$$$$48 from "./sections/CampHero.tsx";
import * as $$$$$$49 from "./sections/HelpFaq.tsx";
import * as $$$$$$50 from "./sections/DecoCamp/PricingSection.tsx";
import * as $$$$$$51 from "./sections/Page.tsx";
import * as $$$$$$52 from "./sections/CampMentor.tsx";
import * as $$$$$$53 from "./sections/PricingValue.tsx";
import * as $$$$$$54 from "./sections/HeroPost.tsx";
import * as $$$$$$55 from "./sections/Community.tsx";
import * as $$$$$$56 from "./sections/RankingList.tsx";
import * as $$$$$$57 from "./sections/HelpBlogPosts.tsx";
import * as $$$$$$58 from "./sections/Live Projects/ProjectsGrid.tsx";
import * as $$$$$$59 from "./sections/Live Projects/LiveProjects.tsx";
import * as $$$$$$60 from "./sections/Live Projects/Hero.tsx";
import * as $$$$$$61 from "./sections/FooterBigLogo.tsx";
import * as $$$$$$62 from "./sections/RankingHeader.tsx";
import * as $$$$$$63 from "./sections/Thanks.tsx";
import * as $$$$$$64 from "./sections/ImpactCalculator.tsx";
import * as $$$$$$65 from "./sections/Home/Brands.tsx";
import * as $$$$$$66 from "./sections/JoinOurCommunity.tsx";
import * as $$$$$$67 from "./sections/Whatsapp.tsx";
import * as $$$$$$68 from "./sections/OnThisPage.tsx";
import * as $$$$$$69 from "./sections/Header.tsx";
import * as $$$$$$70 from "./sections/StripePricing.tsx";
import * as $$$$$$71 from "./sections/BlogPostHeader.tsx";
import * as $$$$$$72 from "./sections/WasThisPageHelpful.tsx";
import * as $$$$$$73 from "./sections/CampSteps.tsx";
import * as $$$$$$74 from "./sections/Hub/Integrations.tsx";
import * as $$$$$$75 from "./sections/Hub/SectionSubtitle.tsx";
import * as $$$$$$76 from "./sections/Hub/Heading.tsx";
import * as $$$$$$77 from "./sections/Hub/TemplatePreview.tsx";
import * as $$$$$$78 from "./sections/Hub/TemplatesGrid.tsx";
import * as $$$$$$79 from "./sections/Hub/Advantage.tsx";
import * as $$$$$$80 from "./sections/Hub/Agencies.tsx";
import * as $$$$$$81 from "./sections/Hub/Creator.tsx";
import * as $$$$$$82 from "./sections/Hub/SectionTitle.tsx";
import * as $$$$$$83 from "./sections/Hub/TemplateIframe.tsx";
import * as $$$$$$84 from "./sections/BlogPostSEO.tsx";
import * as $$$$$$85 from "./sections/Content.tsx";
import * as $$$$$$86 from "./sections/MarkdownContent.tsx";
import * as $$$$$$87 from "./sections/PopularTopics.tsx";
import * as $$$$$$88 from "./sections/Benefits.tsx";
import * as $$$$$$89 from "./sections/Features.tsx";
import * as $$$$$$90 from "./sections/Head.tsx";
import * as $$$$$$91 from "./sections/ReCAPTCHA.tsx";
import * as $$$$$$92 from "./sections/MainBanner.tsx";
import * as $$$$$$93 from "./sections/Footer.tsx";
import * as $$$$$$94 from "./sections/Webinar/Content.tsx";
import * as $$$$$$95 from "./sections/Webinar/Hero.tsx";
import * as $$$$$$96 from "./sections/HowCanWeHelp.tsx";
import * as $$$$$$97 from "./sections/ContactUs.tsx";
import * as $$$$$$98 from "./sections/Sidebar.tsx";
import * as $$$$$$99 from "./sections/General/Spacer.tsx";
import * as $$$$$$100 from "./sections/CampComments.tsx";
import * as $$$$$$101 from "./sections/Markdown.tsx";
import * as $$$$$$102 from "./sections/Pricing.tsx";
import * as $$$$$$103 from "./sections/Cms.tsx";
import * as $$$$$$104 from "./sections/Carousel.tsx";
import * as $$$$$$105 from "./sections/Faq.tsx";
import * as $$$$$$106 from "./sections/DepoimentsCarrossel.tsx";
import * as $$$$$$107 from "./sections/Partner.tsx";
import * as $$$$$$108 from "./sections/Case/ArticleYoutubeVideo.tsx";
import * as $$$$$$109 from "./sections/Case/ArticleParagraph.tsx";
import * as $$$$$$110 from "./sections/Case/Case.tsx";
import * as $$$$$$111 from "./sections/Case/ArticleHeader.tsx";
import * as $$$$$$112 from "./sections/Case/ArticleDivider.tsx";
import * as $$$$$$113 from "./sections/Case/ArticleVideo.tsx";
import * as $$$$$$114 from "./sections/Case/ArticleQuote.tsx";
import * as $$$$$$115 from "./sections/Case/ArticleBannerCTA.tsx";
import * as $$$$$$116 from "./sections/Case/ArticleImage.tsx";
import * as $$$$$$117 from "./sections/Case/CaseForm.tsx";
import * as $$$$$$118 from "./sections/Case/ArticleNumbers.tsx";
import * as $$$$$$119 from "./sections/Divider.tsx";
import * as $$$$$$$0 from "./matchers/MatchPath.ts";
import * as $$$$$$$$$0 from "./actions/feedbackDocs.ts";
import * as $$$$$$$$$1 from "./actions/startAlgoliaCrawler.ts";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "functions": {
    "deco-sites/starting/functions/LoadGitHubRaw.ts": $2,
    "deco-sites/starting/functions/LoadGitHubRawPost.ts": $4,
    "deco-sites/starting/functions/LoadGitHubRawPostList.ts": $0,
    "deco-sites/starting/functions/LoadPageProps.ts": $1,
    "deco-sites/starting/functions/psiRankingList.ts": $3,
  },
  "loaders": {
    "deco-sites/starting/loaders/blogPostDetailsLoader.ts": $$$1,
    "deco-sites/starting/loaders/blogPostLoader.ts": $$$4,
    "deco-sites/starting/loaders/blogPostMarkdownLoader.ts": $$$5,
    "deco-sites/starting/loaders/denoLoader.ts": $$$0,
    "deco-sites/starting/loaders/denoTopicsLoader.ts": $$$2,
    "deco-sites/starting/loaders/featuredPosts.ts": $$$3,
  },
  "handlers": {
    "deco-sites/starting/handlers/feed.ts": $$$$0,
  },
  "sections": {
    "deco-sites/starting/sections/About.tsx": $$$$$$10,
    "deco-sites/starting/sections/Benefits.tsx": $$$$$$88,
    "deco-sites/starting/sections/BlogHeader.tsx": $$$$$$8,
    "deco-sites/starting/sections/BlogPostHeader.tsx": $$$$$$71,
    "deco-sites/starting/sections/BlogPostList.tsx": $$$$$$4,
    "deco-sites/starting/sections/BlogPostSEO.tsx": $$$$$$84,
    "deco-sites/starting/sections/Camp/Achievements/Achievements.tsx": $$$$$$17,
    "deco-sites/starting/sections/Camp/Benefits/Benefits.tsx": $$$$$$23,
    "deco-sites/starting/sections/Camp/Benefits/HowItWorks.tsx": $$$$$$22,
    "deco-sites/starting/sections/Camp/DndButtons.tsx": $$$$$$20,
    "deco-sites/starting/sections/Camp/FAQ/Faq.tsx": $$$$$$16,
    "deco-sites/starting/sections/Camp/Gallery.tsx": $$$$$$11,
    "deco-sites/starting/sections/Camp/Hero/Hero.tsx": $$$$$$12,
    "deco-sites/starting/sections/Camp/Images/Carousel.tsx": $$$$$$13,
    "deco-sites/starting/sections/Camp/Mentors/Mentors.tsx": $$$$$$18,
    "deco-sites/starting/sections/Camp/Prices/Prices.tsx": $$$$$$19,
    "deco-sites/starting/sections/Camp/Problem/Problem.tsx": $$$$$$14,
    "deco-sites/starting/sections/Camp/Syllabus/Syllabus.tsx": $$$$$$21,
    "deco-sites/starting/sections/Camp/Theme/Theme.tsx": $$$$$$15,
    "deco-sites/starting/sections/CampComments.tsx": $$$$$$100,
    "deco-sites/starting/sections/CampHero.tsx": $$$$$$48,
    "deco-sites/starting/sections/CampMentor.tsx": $$$$$$52,
    "deco-sites/starting/sections/CampRegistration.tsx": $$$$$$47,
    "deco-sites/starting/sections/CampSteps.tsx": $$$$$$73,
    "deco-sites/starting/sections/Carousel.tsx": $$$$$$104,
    "deco-sites/starting/sections/Case/ArticleBannerCTA.tsx": $$$$$$115,
    "deco-sites/starting/sections/Case/ArticleDivider.tsx": $$$$$$112,
    "deco-sites/starting/sections/Case/ArticleHeader.tsx": $$$$$$111,
    "deco-sites/starting/sections/Case/ArticleImage.tsx": $$$$$$116,
    "deco-sites/starting/sections/Case/ArticleNumbers.tsx": $$$$$$118,
    "deco-sites/starting/sections/Case/ArticleParagraph.tsx": $$$$$$109,
    "deco-sites/starting/sections/Case/ArticleQuote.tsx": $$$$$$114,
    "deco-sites/starting/sections/Case/ArticleVideo.tsx": $$$$$$113,
    "deco-sites/starting/sections/Case/ArticleYoutubeVideo.tsx": $$$$$$108,
    "deco-sites/starting/sections/Case/Case.tsx": $$$$$$110,
    "deco-sites/starting/sections/Case/CaseForm.tsx": $$$$$$117,
    "deco-sites/starting/sections/Cms.tsx": $$$$$$103,
    "deco-sites/starting/sections/Community.tsx": $$$$$$55,
    "deco-sites/starting/sections/ContactUs.tsx": $$$$$$97,
    "deco-sites/starting/sections/Content.tsx": $$$$$$85,
    "deco-sites/starting/sections/CustomizableContent.tsx": $$$$$$1,
    "deco-sites/starting/sections/DecoCamp/PricingSection.tsx": $$$$$$50,
    "deco-sites/starting/sections/Delight.tsx": $$$$$$6,
    "deco-sites/starting/sections/DepoimentsCarrossel.tsx": $$$$$$106,
    "deco-sites/starting/sections/Differentials.tsx": $$$$$$24,
    "deco-sites/starting/sections/Divider.tsx": $$$$$$119,
    "deco-sites/starting/sections/Faq.tsx": $$$$$$105,
    "deco-sites/starting/sections/Features.tsx": $$$$$$89,
    "deco-sites/starting/sections/Footer.tsx": $$$$$$93,
    "deco-sites/starting/sections/FooterBigLogo.tsx": $$$$$$61,
    "deco-sites/starting/sections/General/Spacer.tsx": $$$$$$99,
    "deco-sites/starting/sections/Head.tsx": $$$$$$90,
    "deco-sites/starting/sections/Header.tsx": $$$$$$69,
    "deco-sites/starting/sections/HelpBlogPosts.tsx": $$$$$$57,
    "deco-sites/starting/sections/HelpFaq.tsx": $$$$$$49,
    "deco-sites/starting/sections/HeroPost.tsx": $$$$$$54,
    "deco-sites/starting/sections/Home/Brands.tsx": $$$$$$65,
    "deco-sites/starting/sections/HowCanWeHelp.tsx": $$$$$$96,
    "deco-sites/starting/sections/Hub/Advantage.tsx": $$$$$$79,
    "deco-sites/starting/sections/Hub/Agencies.tsx": $$$$$$80,
    "deco-sites/starting/sections/Hub/Creator.tsx": $$$$$$81,
    "deco-sites/starting/sections/Hub/Heading.tsx": $$$$$$76,
    "deco-sites/starting/sections/Hub/Integrations.tsx": $$$$$$74,
    "deco-sites/starting/sections/Hub/SectionSubtitle.tsx": $$$$$$75,
    "deco-sites/starting/sections/Hub/SectionTitle.tsx": $$$$$$82,
    "deco-sites/starting/sections/Hub/TemplateIframe.tsx": $$$$$$83,
    "deco-sites/starting/sections/Hub/TemplatePreview.tsx": $$$$$$77,
    "deco-sites/starting/sections/Hub/TemplatesGrid.tsx": $$$$$$78,
    "deco-sites/starting/sections/ImpactCalculator.tsx": $$$$$$64,
    "deco-sites/starting/sections/Integration.tsx": $$$$$$5,
    "deco-sites/starting/sections/JoinOurCommunity.tsx": $$$$$$66,
    "deco-sites/starting/sections/Links.tsx": $$$$$$2,
    "deco-sites/starting/sections/Live Projects/Hero.tsx": $$$$$$60,
    "deco-sites/starting/sections/Live Projects/LiveProjects.tsx": $$$$$$59,
    "deco-sites/starting/sections/Live Projects/ProjectsGrid.tsx": $$$$$$58,
    "deco-sites/starting/sections/MainBanner.tsx": $$$$$$92,
    "deco-sites/starting/sections/Markdown.tsx": $$$$$$101,
    "deco-sites/starting/sections/MarkdownContent.tsx": $$$$$$86,
    "deco-sites/starting/sections/NRF/BlogPosts.tsx": $$$$$$26,
    "deco-sites/starting/sections/NRF/Brands.tsx": $$$$$$45,
    "deco-sites/starting/sections/NRF/CallToAction.tsx": $$$$$$32,
    "deco-sites/starting/sections/NRF/Contact.tsx": $$$$$$30,
    "deco-sites/starting/sections/NRF/DecoFooter.tsx": $$$$$$35,
    "deco-sites/starting/sections/NRF/Editor.tsx": $$$$$$31,
    "deco-sites/starting/sections/NRF/EditorMobile.tsx": $$$$$$27,
    "deco-sites/starting/sections/NRF/Features.tsx": $$$$$$41,
    "deco-sites/starting/sections/NRF/FeaturesWithImage.tsx": $$$$$$37,
    "deco-sites/starting/sections/NRF/Grid.tsx": $$$$$$29,
    "deco-sites/starting/sections/NRF/Header.tsx": $$$$$$38,
    "deco-sites/starting/sections/NRF/Hero.tsx": $$$$$$44,
    "deco-sites/starting/sections/NRF/HeroFlat.tsx": $$$$$$39,
    "deco-sites/starting/sections/NRF/ImageSection.tsx": $$$$$$25,
    "deco-sites/starting/sections/NRF/PageWrapper.tsx": $$$$$$28,
    "deco-sites/starting/sections/NRF/PlatformContact.tsx": $$$$$$40,
    "deco-sites/starting/sections/NRF/Pricing.tsx": $$$$$$43,
    "deco-sites/starting/sections/NRF/PricingValue.tsx": $$$$$$33,
    "deco-sites/starting/sections/NRF/Questions.tsx": $$$$$$42,
    "deco-sites/starting/sections/NRF/TextLines.tsx": $$$$$$34,
    "deco-sites/starting/sections/NRF/Thanks.tsx": $$$$$$36,
    "deco-sites/starting/sections/OnThisPage.tsx": $$$$$$68,
    "deco-sites/starting/sections/Page.tsx": $$$$$$51,
    "deco-sites/starting/sections/Partner.tsx": $$$$$$107,
    "deco-sites/starting/sections/PopularDocuments.tsx": $$$$$$3,
    "deco-sites/starting/sections/PopularTopics.tsx": $$$$$$87,
    "deco-sites/starting/sections/Pricing.tsx": $$$$$$102,
    "deco-sites/starting/sections/PricingValue.tsx": $$$$$$53,
    "deco-sites/starting/sections/QuillText.tsx": $$$$$$9,
    "deco-sites/starting/sections/RankingAnalyze.tsx": $$$$$$0,
    "deco-sites/starting/sections/RankingHeader.tsx": $$$$$$62,
    "deco-sites/starting/sections/RankingList.tsx": $$$$$$56,
    "deco-sites/starting/sections/ReCAPTCHA.tsx": $$$$$$91,
    "deco-sites/starting/sections/SectionList.tsx": $$$$$$7,
    "deco-sites/starting/sections/Sidebar.tsx": $$$$$$98,
    "deco-sites/starting/sections/StripePricing.tsx": $$$$$$70,
    "deco-sites/starting/sections/Thanks.tsx": $$$$$$63,
    "deco-sites/starting/sections/TripletBanner.tsx": $$$$$$46,
    "deco-sites/starting/sections/WasThisPageHelpful.tsx": $$$$$$72,
    "deco-sites/starting/sections/Webinar/Content.tsx": $$$$$$94,
    "deco-sites/starting/sections/Webinar/Hero.tsx": $$$$$$95,
    "deco-sites/starting/sections/Whatsapp.tsx": $$$$$$67,
  },
  "matchers": {
    "deco-sites/starting/matchers/MatchPath.ts": $$$$$$$0,
  },
  "actions": {
    "deco-sites/starting/actions/feedbackDocs.ts": $$$$$$$$$0,
    "deco-sites/starting/actions/startAlgoliaCrawler.ts": $$$$$$$$$1,
  },
  "apps": {
    "deco-sites/starting/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/starting/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/starting",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
